#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

use 5.010001;
use strict;
use warnings;
use Log::ger;
#use Log::ger::Screen;

use File::chdir;
use File::Slurper qw(read_binary);
use File::Temp qw(tempdir);
use File::Which qw(which);
use CLI::MetaUtil::Getopt::Long qw(GetOptionsCLIWrapper);
use IPC::System::Options 'system', -log=>1, -die=>1;

my @files;
Getopt::Long::Configure("gnu_getopt", "no_ignore_case", "pass_through");

my $fail;

GetOptionsCLIWrapper(
    cli => 'diff',
    add_opts => {
        '<>' => sub {
            my $filename = $_[0];
            unless (-f $filename) {
                warn "diff-pdf-text: No such file or not a file: '$filename'\n";
                $fail++;
                return;
            }

            require App::PDFUtils;
            my $res = App::PDFUtils::convert_pdf_to_text(
                file => $filename,
                fmt => 1,
                return_output_file => 1,
            );
            my $file;
            if ($res->[0] == 304) {
                $file = $_[0];
            } elsif ($res->[0] == 200) {
                $file = $res->[2];
            } else {
                die "Can't convert PDF '$_[0]' to text: $res->[0] - $res->[1]";
            }
            push @CLI::MetaUtil::Getopt::Long::cli_argv, $file;
        },
    },
);

exit 1 if $fail;

require File::Which;
my $diff_cmd =
    $ENV{DIFF_PDF_TEXT_DIFF_CMD} //
    $ENV{DIFF_CMD} //
    (File::Which::which("diffwc") ? "diffwc" : undef) // "diff";

require IPC::System::Options;
IPC::System::Options::system(
    {log=>1},
    $diff_cmd, "-ruN", @ARGV,
);

# ABSTRACT: Diff the text of two PDF documents
# PODNAME:

=head1 SYNOPSIS

Use like you would use the Unix command B<diff>:

 % diff-pdf-text [options] <FILE>...


=head1 DESCRIPTION

This is a wrapper for the Unix command B<diff>. It assumes that each input file
is a PDF file and tries to convert the file to text first using L<App::PDFUtils>
(which in turn uses B<pdftotext> CLI utility). It then passes the converted
text C<< diff -ruN >> command.


=head1 OPTIONS

These are options that are interpreted by B<diff-pdf-text> and not passed to
B<diff>.

B<Please specify these options before file names.>

=over

=back


=head1 ENVIRONMENT

=head2 DEBUG

If set to true, do not cleanup temporary directories.

=head1 DIFF_CMD

String. Can be used to set path to diff command. See also
L</DIFF_PDF_TEXT_DIFF_CMD> which takes precedence.

=head2 DIFF_PDF_TEXT_DIFF_CMD

String. Can be used to set path to diff command. The defaultl is L<diffwc> if
available in PATH, or C<diff>. Takes precedence over L</DIFF_CMD>.


=head1 SEE ALSO

Unix command L<diff>.
